### ISSUE TITLE
Request: Relicensing?

### ISSUE THREAD

**Issue by ColinGilbert** [wchristian/ogldev#1]
Hi,

I really like your tutorials; they are very enlightening and your service to the community is an act of generosity that both myself and many others appreciate greatly. However, the only problem is that the code is licensed as GPL3, which makes it completely inappropriate for many markets (iOS, Steam, contracts with employers requiring ownership of the resulting code.)

If feasible to do so, it would be really, really appreciated if you could relicense under more liberal (non-viral) terms. Please don't get me wrong; I would love it greatly if strong open-source were the norm, but unfortunately current market conditions aren't very friendly to such licensing.

Something such as the Apache 2 license would be a near-perfect mix of liberal licensing and copyleft; I would personally be glad to contribute any fixes and improvements to this codebase.

Thank you for your time,
Colin

**Comment by wchristian** [comment]
Two questions:
1. Are you sure you got the right guy? I'm just converting the C tutorials to Perl, i'm not the one writing them.
2. If you're sure you got the right guy, i'm unclear as to whether i can relicense them as derivative works to something else. Personally i'd release anything i do as CC0, but i don't know enough about the legal ramifications in this case.

**Comment by ColinGilbert** [comment]
Oh! Well, that explains all the perl files... Thanks for your time anyhow! :)

**Comment by wchristian** [comment]
Cheers. :)
