### ISSUE TITLE
cannot execute on ubuntu64

### ISSUE THREAD

**Issue by Juude** [wchristian/ogldev#2]
When I try to execute the example tutorial04, I found the error

```
Error compiling shader type 35633: '0:1(10): error: GLSL 3.30 is not supported.    Supported versions are: 1.10, 1.20, 1.30, and 1.00 ES
```

But after I changed the to version 130, I got this error 

```
Error compiling shader type 35633: '0:2(1): error: syntax error, unexpected NEW_IDENTIFIER
```

**Comment by wchristian** [comment]
Sorry for being so late, and i guess you already figured this out, but it looks like your graphics card simply isn't new enough.
